# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalcCal' do
  target 'TestTargetName' do
    inherit! :search_paths
  end
  
  use_frameworks!
  pod 'Firebase/Auth'

end
